spring:
  application.name: pdfmaker
  profiles.active: dev

  cache:
    type: redis

  webflux:
    base-path: /api
    multipart:
      max-disk-usage-per-part: 20MB

  jackson:
    time-zone: "Asia/Seoul"
    serialization:
      write-dates-as-timestamps: true

  mustache:
    enabled: false
    prefix: classpath:/mustaches/

server:
  port: 8080
  forward-headers-strategy: native
  compression:
    enabled: true
    mime-types: text/html,application/xhtml+xml,application/xml,text/plain,application/json,*/*
    min-response-size: 1024



logging:
  level:
    root: INFO
    org.springframework: INFO
    net.rubyworks.pdfmaker: DEBUG



---
spring:
  config.activate.on-profile: dev

app_props:
  allowedOriginPatterns: '*localhost*'
  pdf:
    master-secret: helloworld 



---
spring:
  config.activate.on-profile: product
  
app_props:
  allowedOriginPatterns: '*localhost*'
  pdf:
    master-secret: helloworld 
  

#springdoc:
#  api-docs:
#    path: /swagger/docs


#logging.level.org.springframework.web.server.adapter.HttpWebHandlerAdapter: TRACE

